/**
 * Created by Maple on 17/3/21.
 */

export const SELECT_SUGGEST_QUERY = 'SELECT_SUGGEST_QUERY';
export const RESET_SUGGEST_QUERY = 'RESET_SUGGEST_QUERY';
export const REQUEST_MOVIE_DATA = 'REQUEST_MOVIE_DATA';
export const RECEIVE_MOVIE_DATA = 'RECEIVE_MOVIE_DATA';

export const SELECT_MOVIE = 'SELECT_MOVIE';