/**
 * Created by Maple on 17/3/21.
 */

export const SELECT_DEFAULT_QUERY = 'SELECT_DEFAULT_QUERY';
export const REQUEST_MOVIE_DATA = 'REQUEST_MOVIE_DATA';
export const RECEIVE_MOVIE_DATA = 'RECEIVE_MOVIE_DATA';